#!/usr/bin/env python3
"""Render the model-selection audit (markdown) from tests/model_selection_matrix.py results.
    python3 tests/model_selection_report.py WORKDIR OUT.md
WORKDIR holds results.json (matrix), and optionally agent_routing.jsonl (tests/agent_routing_check.py)
and hf-check.txt (tests/check-hf-manifest.py output)."""
import collections, json, os, re, subprocess, sys, time
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK, OUT = sys.argv[1], sys.argv[2]
rows = json.load(open(os.path.join(WORK, "results.json")))
M = json.load(open(os.path.join(ROOT, "config", "models-manifest.json")))["candidates"]
SHORT = {"LFM2.5-1.2B-Instruct-Q4_K_M.gguf": "LFM-1.2B", "Qwen3.5-2B-Q4_K_M.gguf": "Qwen-2B",
         "Laya-Q8_0.gguf": "Laya-Q8", "LFM2.5-350M-Q4_K_M.gguf": "LFM-350M", "Qwen3.5-0.8B-Q4_K_M.gguf": "Qwen-0.8B",
         "Julia-1-Q8_0.gguf": "Julia-1", "Qwen3.5-4B-Q4_K_M.gguf": "Qwen-4B", "HY-MT1.5-1.8B-Q4_K_M.gguf": "HY-MT-1.8B",
         "Qwen3.5-0.8B-Japanese-SFT-v2-Q4_K_M.gguf": "JA-SFT-0.8B"}
DEF_URLS = sorted(f"https://huggingface.co/{c['repo']}/resolve/{c['revision']}/{c['file']}" for c in M if c["pick"] == "default")
URL2 = {f"https://huggingface.co/{c['repo']}/resolve/{c['revision']}/{c['file']}": SHORT.get(c["file"], c["file"]) for c in M}
commit = subprocess.run(["git", "-C", ROOT, "log", "-1", "--format=%h %s"], capture_output=True, text=True).stdout.strip()
ROLES = ("general", "coder", "decision", "language")


def sm(v):
    if not v:
        return "–"
    if not v.get("model"):
        return "(listed, no file)" if not v.get("hf") else "hf:" + v["hf"]
    return SHORT.get(v["model"], v["model"])


def dl(r):
    if not r["downloads"]:
        return "none"
    if sorted(r["downloads"]) == DEF_URLS:
        return "D3"
    return "+".join(URL2.get(u, u) for u in r["downloads"])


def st(r):
    s = r["status"]
    if s == "ok" and r.get("router_error"):
        return "router exit: " + r["router_error"].split("E srv")[-1].strip()[:60]
    if s == "ok":
        return "ok"
    s = re.sub(r"\x1b\[[0-9;]*m", "", s)
    s = s.replace("error: ", "")
    s = re.sub(r"/\S*/sb/\d+", "<ROOT>", s)
    return "FAIL: " + s[:100]


def par(r, key):
    return "/".join((r["roles"][x] or {}).get(key) or "–" for x in ROLES if r["roles"][x]) or "–"


def mmax(r):
    a = r["argv"]
    return next((a[i + 1] for i, v in enumerate(a) if v == "--models-max" and i + 1 < len(a)), "–")


def lj(r):
    j = r.get("language_json") or {}
    return f"{j.get('locale', '')}/{j.get('mode', '')}" + (f"/swap={j['swapped']}" if j.get("swapped") else "") if j else "–"


def esc(s):
    return str(s).replace("|", "\\|")


def table(head, body):
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += ["| " + " | ".join(esc(c) for c in b) + " |" for b in body]
    return "\n".join(out)


L = []
w = L.append
w("# Model-selection audit: code-bootstraps-llama.cpp")
w("")
w(f"- Commit: `{commit}` (main). Generated {time.strftime('%Y-%m-%d %H:%M')} PT on the box (Linux x86_64, 8 threads, 16 GB).")
w("- Generated by `tests/model-selection-matrix.sh` (→ `tests/model_selection_matrix.py` + `tests/model-selection-matrix.ps1`), "
  "`tests/check-hf-manifest.py`, `tests/agent_routing_check.py`, rendered by `tests/model_selection_report.py`.")
w(f"- {len(rows)} combinations. Each one runs the REAL launcher scripts (start.sh / start.command / Termux start.sh / "
  "start.ps1 / serve.sh / serve.ps1) in a sandbox copy of the repo. Each distinct resulting llama-server command line + "
  "effective preset + model tree is then started on the REAL pinned router (`bin/llama-b11374-linux-x64-cpu/llama-server`, "
  "router mode, empty LLAMA_CACHE unless the test sets one). The table records what the router itself resolved for each "
  "role (`GET /models` → `status.args`), not what the scripts meant to do.")
w("- Stubs: `curl`/`curl.exe` (records the HF URL and writes a placeholder; `sha256sum`/`Get-FileHash` return the manifest hash for "
  "placeholders), the llama-server that the launcher execs (records argv, env and preset), `uname`/`sysctl`/`defaults` (macOS: "
  "Apple Silicon with 4 performance cores), `getprop` + `$PREFIX` (Termux), and under pwsh `Get-CimInstance` (RAM 16 GB, or 4 GB in "
  "profile-auto rows), `Get-Culture` (returns the LOCALE column), `fetch-llama.ps1`, `open-ui.ps1`.")
w("- Sections: Legend, Results by check (a)-(h), Check summary, Mismatches and risks, Summary for Brian (what Windows downloads and "
  "runs), Appendix (every main-grid combination).")
w("- NOT covered (needs the real machine): Windows PowerShell 5.1 parsing, NTFS directory order, real `Get-Culture` on a ja-JP Windows, "
  "real downloads and their hashing, GPU (`--n-gpu-layers auto` / `--fit on` choose layers at load time), real macOS/Android.")
w("")
w("## Legend")
w("")
w("`D3` = exactly the three default downloads, at pinned revisions, hash-checked after download:")
w("")
w(table(["pick", "role", "file", "HF repo", "revision", "sha256", "bytes"],
        [[c["pick"], c["role"], c["file"], c["repo"], c["revision"], c["sha256"], f"{c['bytes']:,}"] for c in M]))
w("")
w(f"Default download total: {sum(c['bytes'] for c in M if c['pick'] == 'default'):,} bytes (~2.46 GB). "
  "Short names: LFM-1.2B, Qwen-2B, Laya-Q8 (defaults); JA-SFT-0.8B, HY-MT-1.8B, Qwen-4B, Qwen-0.8B, LFM-350M, Julia-1 (optional).")
w("")
w("Install column: `defaults` = only the three defaults; `optin` = defaults + JA-SFT-0.8B (`models-optional/locale/ja/`) + "
  "HY-MT-1.8B (`models-optional/language/`) already present, i.e. what `fetch-models -Pick locale-ja` + `-Pick language` leave behind. "
  "Per-role parameter columns are general/coder/decision[/language]. ngl is `auto` with `--fit on` everywhere.")
w("")

# ---------------------------------------------------------------- checks summary
main = [r for r in rows if r["grid"] == "main"]
ok = [r for r in main if r["status"] == "ok" and not r.get("router_error")]
w("## Results by check")
w("")
# (b)
classes = collections.Counter((dl(r), sm(r["roles"]["general"]), sm(r["roles"]["coder"]), sm(r["roles"]["decision"]),
                               sm(r["roles"]["language"]), tuple(r["extra_models"])) for r in ok)
w("### (b)/(c) Downloads and served models over the main grid")
w("")
w(f"Main grid: {len(main)} combinations (6 launchers × 2 PROFILE × 6 LANGUAGE_MODE × 10 locales × 2 installs); "
  f"{len(ok)} start, {len(main) - len(ok)} refuse to start (all listed below). Outcome classes among the ones that start:")
w("")
body = []
for (d, g, c, de, la, ex), n in classes.most_common():
    sel = [r for r in ok if (dl(r), sm(r["roles"]["general"]), sm(r["roles"]["coder"]), sm(r["roles"]["decision"]),
                             sm(r["roles"]["language"]), tuple(r["extra_models"])) == (d, g, c, de, la, ex)]
    modes = sorted({r["mode"] for r in sel}); locs = sorted({r["locale"] for r in sel}); ins = sorted({r["install"] for r in sel})
    lau = sorted({r["launcher"] for r in sel})
    body.append([n, d, g, c, de, la, ",".join(ex) or "none", ", ".join(lau), ", ".join(modes), ", ".join(locs), ", ".join(ins)])
w(table(["n", "downloads", "general", "coder", "decision", "language", "extra models", "launchers", "LANGUAGE_MODE", "locales", "install"], body))
w("")
fails = collections.Counter((r["launcher"], r["mode"], st(r)) for r in main if r not in ok)
w("Combinations that refuse to start (loud error, nothing served):")
w("")
w(table(["launcher", "LANGUAGE_MODE", "error", "n"], [[a, b, c, n] for (a, b, c), n in sorted(fails.items())]))
w("")
# params
pp = collections.Counter((r["launcher"], r["profile"], par(r, "ctx"), par(r, "np"), par(r, "kvslot"), par(r, "t"), par(r, "tb"),
                          par(r, "ngl"), mmax(r)) for r in ok if not r["roles"]["language"])
w("Per-role parameters (rows without a language slot; the language slot adds ctx 8192 default / 4096 lowram, parallel 1):")
w("")
w(table(["launcher", "PROFILE", "ctx g/c/d", "parallel", "kv-per-slot", "threads", "threads-batch", "ngl", "models-max", "n"],
        [list(k) + [n] for k, n in sorted(pp.items())]))
w("")
pa = [r for r in rows if r["grid"] == "profile-auto"]
w("PROFILE=auto (RAM-based):")
w("")
w(table(["launcher", "RAM (stub)", "locale", "status", "ctx g/c/d", "parallel", "models-max"],
        [[r["launcher"], f"{r['mem'] // 2**30} GB" if r["mem"] else "box 16 GB", r["locale"], st(r), par(r, "ctx"), par(r, "np"), mmax(r)] for r in pa]))
w("")
tl = [r for r in rows if r["grid"] == "tools"]
tc = collections.Counter((dl(r), sm(r["roles"]["general"]), sm(r["roles"]["coder"]), sm(r["roles"]["decision"]), st(r)) for r in tl)
w(f"TOOLS grid ({len(tl)} combinations: 6 launchers × TOOLS auto/full/lean/'' × 2 PROFILE × native/swap, ja_JP, optin install): "
  "TOOLS never changes downloads or models:")
w("")
w(table(["downloads", "general", "coder", "decision", "status", "n"], [list(k) + [n] for k, n in tc.most_common()]))
w("")

# ---------------------------------------------------------------- locale
w("### (d) Locale parsing")
w("")
w("LANGUAGE_MODE=swap, optin install (JA-SFT and HY-MT present), locale from the OS (LANG / AppleLocale / Android getprop / Get-Culture):")
w("")
lau = ["start.sh", "start.command", "termux", "start.ps1", "serve.sh", "serve.ps1"]
idx = {(r["launcher"], r["profile"], r["mode"], r["locale"], r["install"]): r for r in main}
body = []
for loc in ["en_US", "ja_JP", "ja-JP", "ja_JP.UTF-8", "Japanese_Japan.932", "zh_CN", "zh-Hant-TW", "de_DE", "C", "(unset)"]:
    cells = [loc]
    for l in lau:
        r = idx[(l, "default", "swap", loc, "optin")]
        cells.append(f"{lj(r)} → G={sm(r['roles']['general'])}" if r["status"] == "ok" else st(r)[:50])
    body.append(cells)
w(table(["locale"] + lau, body))
w("")
w("Same, LANGUAGE_MODE unset (= the shipped default, native), and interpret:")
w("")
for mode in ("(unset)", "interpret"):
    body = []
    for loc in ["en_US", "ja_JP", "ja-JP", "Japanese_Japan.932", "zh-Hant-TW", "de_DE", "(unset)"]:
        cells = [loc]
        for l in lau:
            r = idx[(l, "default", mode, loc, "optin")]
            cells.append(f"{lj(r)} G={sm(r['roles']['general'])} L={sm(r['roles']['language'])}" if r["status"] == "ok" else st(r)[:50])
        body.append(cells)
    w(f"LANGUAGE_MODE={mode}:")
    w("")
    w(table(["locale"] + lau, body))
    w("")
le = [r for r in rows if r["grid"] == "locale-env"]
w("Explicit `LOCALE` env (overrides the OS locale), en_US OS, optin install:")
w("")
body = []
for el in ["ja", "ja-JP", "JA_jp", "Japanese_Japan.932", "zh-TW", "de", "en"]:
    for mode in ("native", "swap", "interpret"):
        cells = [el, mode]
        for l in lau:
            r = next(x for x in le if x["launcher"] == l and x["explicit_locale"] == el and x["mode"] == mode)
            cells.append(f"{lj(r)} G={sm(r['roles']['general'])} L={sm(r['roles']['language'])}" if r["status"] == "ok" else st(r)[:45])
        body.append(cells)
w(table(["LOCALE", "mode"] + lau, body))
w("")

# ---------------------------------------------------------------- parity
w("### (a) sh vs ps1 parity")
w("")
key = lambda r: (r["grid"], r["profile"], r["mode"], r["locale"], r["install"], r["tools"], r["explicit_locale"])
ids = {(r["launcher"],) + key(r): r for r in rows if r["grid"] in ("main", "tools", "locale-env")}


def sections(p):
    s, cur = {}, None
    for l in (p or "").splitlines():
        l = l.strip()
        if not l or l.startswith(";"):
            continue
        m = re.match(r"\[(.*)\]$", l)
        if m:
            cur = m.group(1); s[cur] = {}; continue
        k, _, v = l.partition("="); s.setdefault(cur, {})[k.strip()] = v.strip()
    return s


body = []
for a, b in (("start.sh", "start.ps1"), ("serve.sh", "serve.ps1"), ("start.sh", "start.command"), ("start.sh", "termux")):
    c = collections.Counter(); exs = []
    for k, r in ids.items():
        if k[0] != a:
            continue
        r2 = ids.get((b,) + k[1:])
        if not r2:
            continue
        c["pairs"] += 1
        if (r["status"] == "ok") != (r2["status"] == "ok"):
            c["status differs"] += 1; exs.append(f"{k[2]}/{k[3]}")
            continue
        if r["status"] != "ok":
            c["both refuse"] += 1; continue
        c["both start"] += 1
        c["preset bytes equal"] += r["preset"] == r2["preset"]
        c["preset semantically equal"] += sections(r["preset"]) == sections(r2["preset"])
        c["downloads equal"] += r["downloads"] == r2["downloads"]
        c["router roles+params equal"] += r["roles"] == r2["roles"]
        c["models-max equal"] += mmax(r) == mmax(r2)
        c["language.json equal (parsed)"] += r["language_json"] == r2["language_json"]
    body.append([f"{a} vs {b}", c["pairs"], c["both start"], c["both refuse"], c["status differs"], c["downloads equal"],
                 c["preset bytes equal"], c["preset semantically equal"], c["router roles+params equal"], c["models-max equal"],
                 c["language.json equal (parsed)"], ", ".join(sorted(set(exs)))[:200] or "–"])
w(table(["pair", "pairs", "both start", "both refuse", "status differs", "downloads =", "preset bytes =", "preset semantic =",
         "router roles/params =", "models-max =", "language.json =", "status differs for (PROFILE/LANGUAGE_MODE)"], body))
w("")
w("Notes: start.command / Termux differ from start.sh only where intended (macOS threads = performance cores = 4 in the stub; "
  "Termux PROFILE auto → lowram). The only preset byte differences between sh and ps1 are in lowram rows: ps1 builds the overlay "
  "from a plain `@{}` Hashtable, so the order of the added `ctx-size`/`parallel` lines in [general]/[decision] changes from process "
  "to process (.NET randomizes string hashes; confirmed by running the same Hashtable 6 times: 3 orders each way). The keys and values "
  "are identical, and llama-server does not care about the order. language.json is written by printf in sh and ConvertTo-Json in "
  "ps1, so the parsed content is equal but the bytes are not. The only status differences are LANGUAGE_MODE=auto with a non-English locale: "
  "sh refuses, ps1 accepts it as native (see risks).")
w("")

# ---------------------------------------------------------------- HF
w("### (e) Manifest vs Hugging Face (re-verified live via the HF API tree endpoint at each pinned revision)")
w("")
hf = os.path.join(WORK, "hf-check.txt")
if os.path.exists(hf):
    w(table(["pick", "role", "repo", "file", "result"], [l.rstrip("\n").split("\t") for l in open(hf) if l.count("\t") >= 4]))
w("")
w("All revisions are 40-hex commit SHAs. The only `model =` paths in config/models-preset.ini are the two [locale.ja.*] entries and "
  "both are exactly the manifest's locale-ja dir + file. Default roles are not named in the preset: the router names each "
  "`models/<role>/` directory after the role and loads the single .gguf inside it (see (f)).")
w("")

# ---------------------------------------------------------------- decoys
w("### (f) Decoy .gguf files (real router)")
w("")
DESC = {"role-dir": "5 extra .gguf in models/coder/ (aaa-decoy, zzz-decoy, Qwen3.5-4B-Q4_K_M, decoy-1, decoy-2)",
        "top-level": "models/decoy.gguf", "extra-dir": "models/extra/decoy.gguf",
        "mmproj": "models/coder/decoy-mmproj-F16.gguf", "draft": "models/coder/mtp-decoy.gguf",
        "stale-part": "models/coder/Qwen3.5-0.8B-Q4_K_M.gguf.part and old.gguf.bad", "inactive": "models-inactive/coder/Qwen3.5-0.8B-Q4_K_M.gguf",
        "fallback-installed": "a previous --fallback run left Qwen3.5-0.8B as the coder (2B parked in models-inactive)",
        "hf-cache": "LLAMA_CACHE has an HF-cache-layout someorg/Decoy-GGUF Q4_K_M",
        "language-dir": "models-optional/language/AAA-decoy.gguf next to HY-MT (interpret, ja_JP)"}
dz = [r for r in rows if r["grid"] == "decoy"]
body = []
for r in dz:
    rr = r["roles"]
    body.append([r["label"], DESC.get(r["label"], ""), r["launcher"], st(r), dl(r), sm(rr["general"]), sm(rr["coder"]),
                 sm(rr["decision"]), sm(rr["language"]),
                 os.path.basename((rr["coder"] or {}).get("mmproj") or "") or "–", os.path.basename((rr["coder"] or {}).get("draft") or "") or "–",
                 ",".join(r["extra_models"]) or "–"])
w(table(["case", "decoy", "launcher", "status", "downloads", "general", "coder", "decision", "language", "coder mmproj", "coder draft", "extra router models"], body))
w("")

# ---------------------------------------------------------------- env
w("### (g) Environment overrides and llama-server argument passthrough")
w("")
ez = [r for r in rows if r["grid"] == "env"]
body = []
for r in ez:
    rr = r["roles"]
    body.append([r["label"], r["launcher"], st(r), dl(r), sm(rr["general"]), sm(rr["coder"]), sm(rr["decision"]),
                 par(r, "ctx"), mmax(r), ",".join(r["extra_models"]) or "–"])
w(table(["override", "launcher", "status", "downloads", "general", "coder", "decision", "ctx", "models-max", "extra"], body))
w("")
w("`(listed, no file)`: the role is still a section in the preset but its directory is missing from the models-dir that won, so the "
  "router lists it and fails when it is requested. ps1 passthrough rows run the real `pwsh -NoProfile -File scripts/start.ps1 …` as start.bat does. `/tmp/decoy.gguf` does not exist, "
  "so `-m` rows show the router leaving router mode and exiting. A live run of `scripts/serve.sh -m <real Qwen3.5-0.8B gguf>` on the "
  "real router (port 19446) gave `GET /v1/models` = only that file, and chat requests with model `coder`, `general`, `decision` and "
  "`nonexistent` were ALL answered by Qwen3.5-0.8B with no error (single-model mode ignores the requested name).")
w("")

# ---------------------------------------------------------------- agent
w("### (h) Role names requested by clients")
w("")
ar = os.path.join(WORK, "agent_routing.jsonl")
if os.path.exists(ar):
    c = collections.Counter()
    for l in open(ar):
        d = json.loads(l)
        c[(d["mode"], "ja prompt" if re.search(r"[^\x00-\x7f]", d["prompt"]) else "en prompt",
           "en" if d["locale"] == "en" else "non-en (ja, ja-JP, ja_JP, zh, de)", ", ".join(f"{k}={v}" for k, v in d["env"].items()) or "–",
           d["rc"], ", ".join(sorted(set(d["models"]))))] += 1
    w("scripts/agent.py against a fake server (records the `model` field of every /v1/chat/completions request):")
    w("")
    w(table(["--language-mode", "prompt", "--locale", "env", "rc", "models requested", "n"], [list(k) + [n] for k, n in sorted(c.items())]))
    w("")
w("- agent.py: tool loop always uses `--model` (default `coder`, env `AGENT_MODEL`); `language` is requested only in interpret mode "
  "with a non-English prompt (translate in, localize out). In swap mode it still asks `coder`; the swapped JA model is used only by "
  "clients that ask for `general` (web UI model picker). LLAMA_ARG_MODEL / MODEL_* do not affect it.")
w("- Web UI: start.sh and lib/open-ui.ps1 open `/?model=coder`; the user can pick any model the router lists (general, coder, decision, "
  "language in interpret mode, plus any extra entries from (f)).")
w("- MCP: config/mcp-servers*.json and scripts/mcp-example-server.py contain no model names; MCP tools run inside the request of "
  "whatever model the client picked. The router's child instances get `tools = get_info` and an empty MCP config from the preset `[*]`.")
w("- No `/v1/systemone`-style endpoint or alias exists; model names = directory names in models/ (+ `language` section).")
w("")
FIND = os.environ.get("FINDINGS", os.path.join(WORK, "findings.md"))   # hand-written risks / summary, optional
if os.path.exists(FIND):
    L.append(open(FIND).read())

# ---------------------------------------------------------------- full table
w("")
w("## Appendix: full main-grid decision table")
w("")
body = []
for r in main:
    rr = r["roles"]
    body.append([r["launcher"], r["profile"], r["mode"], r["locale"], r["install"], st(r), dl(r), sm(rr["general"]), sm(rr["coder"]),
                 sm(rr["decision"]), sm(rr["language"]), par(r, "ctx"), par(r, "np"), par(r, "kvslot"), par(r, "t"), par(r, "ngl"),
                 mmax(r), lj(r)])
w(table(["launcher", "PROFILE", "LANGUAGE_MODE", "locale", "install", "status", "downloads", "general", "coder", "decision", "language",
         "ctx", "parallel", "kv/slot", "threads", "ngl", "models-max", "language.json"], body))
w("")
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} blocks)")
